### ISSUE TITLE
Computer player using Jan Ors crew throws exception when choosing to assign focus or evade token

### ISSUE THREAD

**Issue by Sleet01** [xws-bench/bench#76]
Spotted playing against this tournament list:

_F Captain Rex  Sabines Masterpiece
c Braylen Stramm  Jan Ors  R3-A2  Alliance Overhaul
x Biggs Darklighter  R4-D6  Integrated Astromech
c Thane Kyrell  Jyn Erso  Alliance Overhaul
 , 2017-05-09, 100 Point Dogfight,Other_

Bralen Stramm had activated, selected Bank Right 3, and chosen to assign a Focus token to himself.
The engine froze up at this point.

Last log entry is:
_[Bralen Stramm] select <f> or <e> token [Jan Ors]_

Upon pulling up the inspection window, I saw the following exception:

_all.min.js:804 Uncaught TypeError: Cannot read property '0' of undefined
    at Unit.<anonymous> (http://xws-bench.github.io/bench/js/all.min.js:804:245)
    at Unit.m [as getenemiesinrange] (http://xws-bench.github.io/bench/js/all.min.js:562:328)
    at Unit.<anonymous> (http://xws-bench.github.io/bench/js/all.min.js:776:344)
    at Unit.<anonymous> (http://xws-bench.github.io/bench/js/all.min.js:666:366)
    at q (http://xws-bench.github.io/bench/js/all.min.js:272:180)
    at Object.fireWith [as resolveWith] (http://xws-bench.github.io/bench/js/all.min.js:273:414)
    at Object.h.(anonymous function) [as resolve] (http://xws-bench.github.io/bench/js/all.min.js:277:328)
    at Unit.endnoaction (http://xws-bench.github.io/bench/js/all.min.js:666:440)
    at Unit.endaction (http://xws-bench.github.io/bench/js/all.min.js:667:102)
    at Unit.addfocus (http://xws-bench.github.io/bench/js/all.min.js:627:334)_

**Comment by Sleet01** [comment]
Update: it looks like a function from the Biggs section is getting bound to Braylen, and then getting called from the wrong context.  I'll see if I can track it down.
